### GET /
GET http://localhost:1234

### register a user POST /AUTH/REGISTER
POST http://localhost:1234/auth/register
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### login a user POST /AUTH/LOGIN
POST http://localhost:1234/auth/login
Content-Type: application/json

{
    "username": "login",
    "password": "password"
}
